name: SkillBae Frontend CI CD
on:
  push:
    branches: ["main", "staging"]
  pull_request:
    branches: ["main", "staging"]
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
